import { HR_MEMBER_PERMISSION_CODES, HR_PERMISSIONS } from "@/lib/permissions/hr-codes";
import { PLATFORM_PERMISSIONS } from "@/lib/permissions/codes";

export const ORGANIZATION_STANDARD_ROLE_CATALOG = [
  {
    code: "OWNER",
    nameTh: "เจ้าขององค์กร",
    nameEn: "Organization Owner",
    description: "ผู้มีอำนาจสูงสุดภายในองค์กร จัดการผู้ใช้ บทบาท สาขา และบริการขององค์กร",
    sortOrder: 1,
    permissionCodes: [
      PLATFORM_PERMISSIONS.organizationRead,
      PLATFORM_PERMISSIONS.organizationManage,
      PLATFORM_PERMISSIONS.branchRead,
      PLATFORM_PERMISSIONS.branchManage,
      PLATFORM_PERMISSIONS.userRead,
      PLATFORM_PERMISSIONS.userInvite,
      PLATFORM_PERMISSIONS.userSuspend,
      PLATFORM_PERMISSIONS.userManage,
      PLATFORM_PERMISSIONS.roleRead,
      PLATFORM_PERMISSIONS.roleManage,
      PLATFORM_PERMISSIONS.roleAssign,
      PLATFORM_PERMISSIONS.productRead,
      PLATFORM_PERMISSIONS.planRead,
      PLATFORM_PERMISSIONS.subscriptionRead,
      PLATFORM_PERMISSIONS.auditRead,
      PLATFORM_PERMISSIONS.billingSubscriptionRead,
    ],
  },
  {
    code: "ADMIN",
    nameTh: "ผู้ดูแลระบบองค์กร",
    nameEn: "Organization Administrator",
    description: "ดูแลข้อมูล ผู้ใช้ สาขา และการตั้งค่าการใช้งานประจำวันขององค์กร",
    sortOrder: 2,
    permissionCodes: [
      PLATFORM_PERMISSIONS.organizationRead,
      PLATFORM_PERMISSIONS.branchRead,
      PLATFORM_PERMISSIONS.branchManage,
      PLATFORM_PERMISSIONS.userRead,
      PLATFORM_PERMISSIONS.userInvite,
      PLATFORM_PERMISSIONS.userSuspend,
      PLATFORM_PERMISSIONS.userManage,
      PLATFORM_PERMISSIONS.roleRead,
      PLATFORM_PERMISSIONS.productRead,
      PLATFORM_PERMISSIONS.planRead,
      PLATFORM_PERMISSIONS.subscriptionRead,
      PLATFORM_PERMISSIONS.auditRead,
    ],
  },
  {
    code: "BRANCH_MANAGER",
    nameTh: "ผู้จัดการสาขา",
    nameEn: "Branch Manager",
    description: "ดูแลพนักงานและอนุมัติรายการภายในสาขาที่ได้รับมอบหมาย",
    sortOrder: 3,
    permissionCodes: [
      PLATFORM_PERMISSIONS.organizationRead,
      PLATFORM_PERMISSIONS.branchRead,
      PLATFORM_PERMISSIONS.userRead,
    ],
  },
  {
    code: "BILLING_CONTACT",
    nameTh: "ผู้ประสานงานการเงินและการเรียกเก็บเงิน",
    nameEn: "Billing and Finance Contact",
    description: "ดูข้อมูลใบแจ้งหนี้ การชำระเงิน และประสานงานด้านการเงินขององค์กร",
    sortOrder: 4,
    permissionCodes: [
      PLATFORM_PERMISSIONS.organizationRead,
      PLATFORM_PERMISSIONS.subscriptionRead,
      PLATFORM_PERMISSIONS.productRead,
      PLATFORM_PERMISSIONS.planRead,
      PLATFORM_PERMISSIONS.billingAccountRead,
      PLATFORM_PERMISSIONS.billingCreditRead,
      PLATFORM_PERMISSIONS.billingInvoiceRead,
      PLATFORM_PERMISSIONS.billingPaymentRead,
      PLATFORM_PERMISSIONS.billingContactRead,
      PLATFORM_PERMISSIONS.billingContactManage,
      PLATFORM_PERMISSIONS.billingSubscriptionRead,
    ],
  },
  {
    code: "HR_MANAGER",
    nameTh: "ผู้จัดการฝ่ายบุคคล",
    nameEn: "Human Resources Manager",
    description: "จัดการพนักงาน ตำแหน่ง ตารางงาน เวลา การลา OT และการตั้งค่า HR",
    sortOrder: 10,
    permissionCodes: [
      HR_PERMISSIONS.employeeRead,
      HR_PERMISSIONS.employeeCreate,
      HR_PERMISSIONS.employeeUpdate,
      HR_PERMISSIONS.employeeDeactivate,
      HR_PERMISSIONS.employeeLinkUser,
      HR_PERMISSIONS.employeeRoleAssign,
      HR_PERMISSIONS.scheduleRead,
      HR_PERMISSIONS.scheduleManage,
      HR_PERMISSIONS.schedulePublish,
      HR_PERMISSIONS.attendanceRead,
      HR_PERMISSIONS.attendanceManage,
      HR_PERMISSIONS.attendanceOverride,
      HR_PERMISSIONS.leaveRead,
      HR_PERMISSIONS.leaveManage,
      HR_PERMISSIONS.leaveApprove,
      HR_PERMISSIONS.overtimeRead,
      HR_PERMISSIONS.overtimeManage,
      HR_PERMISSIONS.overtimeApprove,
      HR_PERMISSIONS.departmentManage,
      HR_PERMISSIONS.positionManage,
      HR_PERMISSIONS.shiftRead,
      HR_PERMISSIONS.shiftManage,
      HR_PERMISSIONS.locationManage,
      HR_PERMISSIONS.calendarManage,
      HR_PERMISSIONS.approvalRead,
      HR_PERMISSIONS.approvalManage,
      HR_PERMISSIONS.reportRead,
      HR_PERMISSIONS.settingsManage,
      ...HR_MEMBER_PERMISSION_CODES,
    ],
  },
  {
    code: "PAYROLL_OFFICER",
    nameTh: "เจ้าหน้าที่เงินเดือนและค่าตอบแทน",
    nameEn: "Payroll and Compensation Officer",
    description: "จัดการค่าตอบแทน คำนวณและตรวจสอบเงินเดือน งวดจ่าย และสลิปเงินเดือน",
    sortOrder: 11,
    permissionCodes: [
      HR_PERMISSIONS.employeeRead,
      HR_PERMISSIONS.attendanceRead,
      HR_PERMISSIONS.leaveRead,
      HR_PERMISSIONS.overtimeRead,
      HR_PERMISSIONS.compensationRead,
      HR_PERMISSIONS.compensationManage,
      HR_PERMISSIONS.payrollRead,
      HR_PERMISSIONS.payrollCalculate,
      HR_PERMISSIONS.payrollReview,
      HR_PERMISSIONS.payslipRead,
      HR_PERMISSIONS.payrollScheduleRead,
      HR_PERMISSIONS.payrollScheduleManage,
      HR_PERMISSIONS.payrollPeriodRead,
      HR_PERMISSIONS.payrollPeriodManage,
      HR_PERMISSIONS.reportRead,
      ...HR_MEMBER_PERMISSION_CODES,
    ],
  },
  {
    code: "ORGANIZATION_APPROVER",
    nameTh: "ผู้อนุมัติรายการองค์กร",
    nameEn: "Organization Approver",
    description: "ตรวจสอบและอนุมัติการลา OT การเบิกล่วงหน้า และรายการที่รออนุมัติ",
    sortOrder: 12,
    permissionCodes: [
      HR_PERMISSIONS.employeeRead,
      HR_PERMISSIONS.attendanceRead,
      HR_PERMISSIONS.leaveRead,
      HR_PERMISSIONS.leaveApprove,
      HR_PERMISSIONS.overtimeRead,
      HR_PERMISSIONS.overtimeApprove,
      HR_PERMISSIONS.advanceApprove,
      HR_PERMISSIONS.approvalRead,
      HR_PERMISSIONS.approvalManage,
      HR_PERMISSIONS.reportRead,
      ...HR_MEMBER_PERMISSION_CODES,
    ],
  },
  {
    code: "EMPLOYEE",
    nameTh: "พนักงานทั่วไป",
    nameEn: "Employee",
    description: "ใช้งานข้อมูลส่วนตัว ตารางงาน ลงเวลา การลา OT สลิป และการเบิกล่วงหน้าของตนเอง",
    sortOrder: 20,
    permissionCodes: [...HR_MEMBER_PERMISSION_CODES],
  },
] as const;

export function organizationRoleLabel(code: string): string | null {
  return ORGANIZATION_STANDARD_ROLE_CATALOG.find((role) => role.code === code)?.nameTh ?? null;
}
