/** Stable master codes used by services (never rename once referenced). */

export const MASTER = {
  userProfileStatus: {
    ACTIVE: "ACTIVE",
    DISABLED: "DISABLED",
    PENDING: "PENDING",
  },
  platformRole: {
    SUPER_ADMIN: "SUPER_ADMIN",
    SUPPORT: "SUPPORT",
    BILLING_ADMIN: "BILLING_ADMIN",
    SALES: "SALES",
    ACCOUNT_MANAGER: "ACCOUNT_MANAGER",
  },
  assignmentStatus: {
    ACTIVE: "ACTIVE",
    REVOKED: "REVOKED",
  },
  organizationStatus: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    CLOSED: "CLOSED",
  },
  branchStatus: {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
  },
  membershipStatus: {
    INVITED: "INVITED",
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    REMOVED: "REMOVED",
  },
  organizationRole: {
    OWNER: "OWNER",
    ADMIN: "ADMIN",
    BILLING_CONTACT: "BILLING_CONTACT",
  },
  branchScopeType: {
    ALL_BRANCHES: "ALL_BRANCHES",
    SELECTED: "SELECTED",
    NONE: "NONE",
  },
  productStatus: {
    ACTIVE: "ACTIVE",
    RETIRED: "RETIRED",
  },
  featureStatus: {
    ACTIVE: "ACTIVE",
    RETIRED: "RETIRED",
  },
  planStatus: {
    ACTIVE: "ACTIVE",
    RETIRED: "RETIRED",
  },
  planVersionStatus: {
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED",
    RETIRED: "RETIRED",
  },
  billingCycle: {
    MONTHLY: "MONTHLY",
    YEARLY: "YEARLY",
    MANUAL: "MANUAL",
  },
  subscriptionStatus: {
    TRIAL: "TRIAL",
    ACTIVE: "ACTIVE",
    PAST_DUE: "PAST_DUE",
    SUSPENDED: "SUSPENDED",
    CANCELLED: "CANCELLED",
    EXPIRED: "EXPIRED",
  },
  subscriptionOverrideType: {
    GRANT: "GRANT",
    REVOKE: "REVOKE",
    LIMIT: "LIMIT",
  },
  productMembershipStatus: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    REVOKED: "REVOKED",
  },
  outboxEventStatus: {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    PROCESSED: "PROCESSED",
    FAILED: "FAILED",
    DEAD: "DEAD",
  },
  idempotencyStatus: {
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
  },
  legacyMigrationStatus: {
    PENDING: "PENDING",
    LINKED: "LINKED",
    MIGRATED: "MIGRATED",
    FAILED: "FAILED",
    IGNORED: "IGNORED",
  },
  featureValueType: {
    STRING: "STRING",
    NUMBER: "NUMBER",
    BOOLEAN: "BOOLEAN",
  },
  userInvitationStatus: {
    PENDING: "PENDING",
    AUTH_SENT: "AUTH_SENT",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    PLATFORM_SETUP_FAILED: "PLATFORM_SETUP_FAILED",
    CANCELLED: "CANCELLED",
    EXPIRED: "EXPIRED",
  },
  auditActionType: {
    ORGANIZATION_BOOTSTRAP: "organization.bootstrap",
    ORGANIZATION_CREATE: "organization.create",
    ORGANIZATION_UPDATE: "organization.update",
    ORGANIZATION_SUSPEND: "organization.suspend",
    ORGANIZATION_ROLE_REVOKE: "organization.role.revoke",
    BRANCH_CREATE: "branch.create",
    BRANCH_UPDATE: "branch.update",
    BRANCH_SUSPEND: "branch.suspend",
    USER_INVITE: "user.invite",
    USER_REINVITE: "user.reinvite",
    USER_INVITE_REQUESTED: "user.invite.requested",
    USER_INVITE_SENT: "user.invite.sent",
    USER_INVITE_FAILED: "user.invite.failed",
    USER_REINVITE_REQUESTED: "user.reinvite.requested",
    USER_REINVITE_SENT: "user.reinvite.sent",
    USER_REINVITE_FAILED: "user.reinvite.failed",
    USER_INVITE_ACCEPTED: "user.invite.accepted",
    USER_PLATFORM_SETUP_COMPLETED: "user.platform_setup.completed",
    USER_PLATFORM_SETUP_FAILED: "user.platform_setup.failed",
    USER_ACTIVATE: "user.activate",
    USER_SUSPEND: "user.suspend",
    MEMBERSHIP_CREATE: "membership.create",
    MEMBERSHIP_UPDATE: "membership.update",
    ROLE_ASSIGN: "role.assign",
    ROLE_REMOVE: "role.remove",
    CONTEXT_SWITCH: "context.switch",
    CONTEXT_PLATFORM_ADMIN: "context.platform_admin",
    SUBSCRIPTION_CREATE: "subscription.create",
    SUBSCRIPTION_ACTIVATE: "subscription.activate",
    SUBSCRIPTION_TRIAL: "subscription.trial",
    SUBSCRIPTION_SUSPEND: "subscription.suspend",
    SUBSCRIPTION_CANCEL: "subscription.cancel",
    SUBSCRIPTION_CHANGE_PLAN: "subscription.change_plan",
    CUSTOM_ROLE_CREATE: "custom_role.create",
    CUSTOM_ROLE_UPDATE: "custom_role.update",
    CUSTOM_ROLE_DEACTIVATE: "custom_role.deactivate",
    CUSTOM_ROLE_PERMISSION_ADD: "custom_role.permission.add",
    CUSTOM_ROLE_PERMISSION_REMOVE: "custom_role.permission.remove",
    PRODUCT_CREATE: "product.create",
    PRODUCT_UPDATE: "product.update",
    PLAN_CREATE: "plan.create",
    PLAN_UPDATE: "plan.update",
    ENTITLEMENT_GENERATE: "entitlement.generate",
    ORGANIZATION_ONBOARD: "organization.onboard",
    STAFF_PORTFOLIO_ASSIGN: "staff_portfolio.assign",
    STAFF_PORTFOLIO_REVOKE: "staff_portfolio.revoke",
  },
  entitlementStatus: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    EXPIRED: "EXPIRED",
    REVOKED: "REVOKED",
  },
  onboardingStatus: {
    DRAFT: "DRAFT",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
  },
} as const;

export const ACTIVE_SUBSCRIPTION_STATUS_CODES = [
  MASTER.subscriptionStatus.TRIAL,
  MASTER.subscriptionStatus.ACTIVE,
  MASTER.subscriptionStatus.PAST_DUE,
  MASTER.subscriptionStatus.SUSPENDED,
] as const;
